config/routes.rb
Rails.application.routes.draw do
 
  get 'static_pages/home'
  root 'artists#index'

  get '/home', to: 'home#home'
  
  # Custom Routes To Add Songs To A Billboard
  get 'new_billboard_song/:id', to: 'billboards#new_song', as: 'new_billboard_song'
  post 'add_billboard_song/:id/:song_id', to: 'billboards#add_song', as: 'add_billboard_song'
  delete 'remove_billboard_song/:id/:song_id', to: 'billboards#remove_song', as: 'remove_billboard_song'
  
  resources :artists do
    resources :songs
  end

  resources :billboards do
    resources :songs
  end

  resources :artists do
    resources :billboards 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  # has_many :billboards, dependent: :destroy
  # accepts_nested_attributes_for :songs, 
  #                               :reject_if => lambda { |a| a[:content].blank? }, 
  #                               :allow_destroy => true
                                
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :songs #dependent: :destroy
  # belongs_to :artist, optional: :true
  # accepts_nested_attributes_for :songs, 
  #                               :reject_if => lambda { |a| a[:content].blank? }, 
  #                               :allow_destroy => true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :billboard, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  
  def index
    @artists = Artist.all.order(:name)
  end

  def show
  end

  def new 
    @artist = Artist.new
  end

  def update 
    if @artist.update(artist_params)
      redirect_to artist_path
    else 
      render :edit
    end
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      # redirect_to artist_path(@artist)
      redirect_to artists_path
    else
      render :new
    end
  end

  def edit
  end


  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name)
    end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
 
  before_action :set_billboard, except: [:index, :new, :create]
 
  
  def index
    @billboards = Billboard.all
  end

  def show
    @songs = @billboard.songs
  end

  def edit
  end

  def update 
    if @billboard.update(billboard_params)
      redirect_to billboards_path
    else 
      render :edit
    end
  end

  def new 
    @billboard = Billboard.new
  end


  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to @billboard #need to reference both these ids for this path
    else
      render :new
    end
  end

  def destroy
    @billboard.songs.update_all(billboard_id: nil)
    @billboard.destroy
    redirect_to billboards_path
  end

  def new_song
    @songs = Song.all.order(:title).where(billboard_id: nil)
  end

  def add_song
    @billboard.songs << Song.find(params[:song_id])
    redirect_to billboard_path(@billboard)
  end

  def remove_song
    Song.find(params[:song_id]).update(billboard_id: nil)
    redirect_to billboard_path(@billboard)
  end

  private

    def set_billboard
      @billboard = Billboard.find(params[:id])
    end


    def billboard_params
      params.require(:billboard).permit(:name)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    #GET - /artists/:artist_id/songs
    @songs = @artist.songs.all
  end


  def show
  end

  def new
    @song = @artist.songs.new 
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to artist_song_path(@artist, @song)
    else
      render :edit
    end
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_song_path(@artist, @song) #need to reference both these ids for this path
    else
      render :new
    end
  end


  def destroy
    @song.destroy
    redirect_to artist_songs_path(@artist)
  end

private

  def song_params
    params.require(:song).permit(:title, :artist_name, :album, :rating, :country)
  end

  def set_song
    @song = Song.find(params[:id])
  end

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Artist Name" %>
  </div>
   <%= f.submit class: "ui color3 button" %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form", artist: @artist%>

<br/>
<br/>

<%= link_to "Back", artists_path, class: "ui black button" %>
<%= link_to "Show", artist_path(@artist), class: "ui black button" %>

app/views/artists/index.html.erb
<div class="ui center aligned header">
<br/>
  <h1 class="ui huge header">A R T I S T S</h1>
</div>

<div class="ui center aligned header">
  <h1 class="ui medium header">Choose an Artist Below</p>
</div>

<br/>
<div class="ui center aligned header">
  <%= link_to "Add a New Artist", new_artist_path, class: "ui color3 button" %>
</div>
<br/>
<br/>
<hr/>
<br/>

<div class="ui grid">
  <% @artists.each do |artist| %>
  <div class="sixteen wide mobile eight wide tablet four wide computer column">
    <div class="ui card"> 
      <div class="ui inverted segment"> 
        <div class="content">
          <div class="ui inverted segment"> 
            <div class="ui center aligned header">
              <%= link_to artist.name, artist, class: "ui white inverted header" %>
            </div>
          </div>
        </div>
      </div>
      <div class="content">
        <div class="ui small vertical two buttons">
          <button class="ui basic button">
            <%= link_to 'Edit', edit_artist_path(artist), class: "ui color5 button"%>
          </button>
          <button class="ui basic button">
            <%= link_to 'Delete', artist, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui color6 button" %>
          </button>
        </div>
      </div>
    </div>
  </div>

<% end %>
</div>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render "form", artist: @artist %>

<br/>
<%= link_to "Back", artists_path, class: "ui black button"%>

app/views/artists/show.html.erb
<div class="ui center aligned color8 header">
<br/>
  <h1 class="ui huge color8 header">
  <%= @artist.name %></h1>
<br/>
</div>
<div class="ui inverted center aligned segment">
<br/>
  <div class="content">
      <%=link_to 'View Songs', artist_songs_path(@artist), class: "ui huge inverted button" %>
  <br/>
  <br/>
  <%= link_to 'Edit', edit_artist_path(@artist), class: "ui small inverted button" %>  
  <%= link_to 'Back', artists_path, class: "ui small inverted button" %>
  </div>
  <br/>
</div>

app/views/billboards/_form.html.erb
<%= form_with(model: billboard, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Billboard Name" %>
  </div>
   <%= f.submit class: "ui color3 button" %>
<% end %>

app/views/billboards/edit.html.erb
<h1 class="ui header">Edit <%=@billboard.name%></h1>

<%= render "form", billboard: @billboard%>

<br/>

<%= link_to "Back", billboards_path, class: "ui black button" %>
<%= link_to "Show Billboard", billboard_path(@billboard), class: "ui black button" %>

app/views/billboards/index.html.erb
<div class="ui center aligned header">
<br/>
  <h1 class="ui huge header">B I L L B O A R D S</h1>
</div>

<div class="ui center aligned header">
  <h1 class="ui medium header">Choose a Billboard Below</p>
</div>

<br/>
<div class="ui center aligned header">
  <%= link_to "New billboard", new_billboard_path, class: "ui color3 button" %>
</div>

<br/>
<br/>
<hr/>
<br/>

<div class="ui grid">
 <% @billboards.each do |billboard| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card"> 
        <div class="ui inverted segment"> 
          <div class="content">
            <div class="ui inverted segment"> 
              <div class="ui center aligned header">
                <%= link_to billboard.name, billboard, class: "ui white inverted header" %>
              </div>
            </div>
          </div>
        </div>
        <div class="content">
          <div class="ui small vertical two buttons">
            <button class="ui basic button">
              <%= link_to 'Edit', edit_billboard_path(billboard), class: "ui color7 button" %>
            </button>
            <button class="ui basic button">
              <%= link_to 'Delete', billboard, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui color6 button" %>
            </button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/billboards/new.html.erb
<h1>New Billboard</h1>

<%= render "form", billboard: @billboard %>

<br/>
<%= link_to "Back", billboards_path, class: "ui black button" %>

app/views/billboards/new_song.html.erb
<h1 class="ui header">Add A Song To: '<%= @billboard.name %>'</h1>	
<div class="container">
<div class="ui inverted segment">
  <div class="ui inverted center aligned list">
    <% @songs.each do |song| %>
      <%= link_to song.title, add_billboard_song_path(@billboard, song), method: :post, class:"ui inverted spaced medium header colorpink" %>
    <br/>
  <% end %>
  </div>
</div>
</div>
</br>
<%= link_to 'Back', billboards_path, class: 'ui color6 button' %>

app/views/billboards/show.html.erb
<div class="ui center aligned header">
<br/>
  <h1 class="ui huge header">
      <%= @billboard.name %>
  <br/>
</div>

<div class="content">
  <div class="ui two buttons">
    <button class="ui basic button">
      <%= link_to 'Add Song', new_billboard_song_path(@billboard), class: "ui inverted left floated color3 button" %>
    </button>
    <button class="ui basic button">
      <%= link_to 'Back to Billboards', billboards_path, class: "ui inverted right floated color3 button" %> 
    </button>
  </div>
</div>
</br>
 
<div class="ui inverted segment">
  <div class="ui inverted ordered center aligned list">
  <ol>
   <% if @songs.any? %>
      <% @songs.each do |song| %>
        <li class="ui medium inverted header"><%= song.title %> - <%= song.country %></p>
            <%= link_to 'Go To Song', artist_song_path(song.artist, song), class: "ui mini left attached inverted button" %>
            <%= link_to 'Remove From Billboard', remove_billboard_song_path(@billboard, song), method: :delete, class: "ui mini right attached inverted button"%>
        <br/>
        <br/>
        <br/>
      <% end %>
      </ol>
    </div>
  </div>
    <% else %>
  <div class="center-align" >
    <h2>No Songs On Billboard </h2>
  </div>
<% end %>
</div> 
<br/>

app/views/layouts/_navbar.html.erb
<div class="ui inverted segment">
  <div class="ui inverted secondary pointing menu">
    <a class="item" <%= link_to 'Artists', root_path %>
    </a>
    <a class="item" <%= link_to 'Billboards', billboards_path %>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="ui container">
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_with(model: [@artist, @song ], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, required: true, placeholder: "Song Title" %>
  </div>
  <div class="field">
    <%= f.label :artist_name %>
    <%= f.text_field :artist_name, required: true, placeholder: "Artist" %>
  </div>
  <div class="field">
    <%= f.label :album %>
    <%= f.text_field :album, required: true, placeholder: "Album Title" %>
  </div>
  <div class="field">
    <%= f.label :rating %>
    <%= f.text_field :rating, required: true, placeholder: "Rating" %>
  </div>
  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country, required: true, placeholder: "Rating" %>
  </div>
   <%= f.submit class: "ui color3 button" %>

<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render "form", song: @song%>
<br/>
<%= link_to "Back", artist_songs_path, class: "ui black button" %>
<%= link_to "Show", artist_path(@artist), class: "ui black button"%>

app/views/songs/index.html.erb
<div class="ui center aligned header">
  <h3>SONGS BY:</h3>
  <h1 class="ui large header"><%=@artist.name%></h1>
  <div class="ui small two buttons">
    <button class="ui basic button">
      <%= link_to 'Create a New Song', new_artist_song_path(@artist), class: "ui inverted left floated color3 button" %>
    </button>
    <button class="ui basic button">
      <%= link_to 'Back To Artist', artist_path(@artist), class: "ui inverted right floated color3 button" %>
    </button>
  </div>
</div>


<div class="ui inverted segment">
  <div class="ui inverted big relaxed divided list">
    <% @songs.each do |song| %>
    <div class="item">
      </br>
       <a class="item"> <%= link_to song.title, artist_song_path(@artist, song), class: "ui list item"%>
        <% end %> </a>
      </div>
    </div>
  </div>
  </br>
</div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render "form", song: @song%>
<br/>
<%= link_to "Back", artist_songs_path, class: "ui black button"%>
<%= link_to "Show", artist_path(@artist), class: "ui black button" %>

app/views/songs/show.html.erb
<div class="ui center aligned header">
  <h1><%= @song.title %></h1>
  <div class="ui inverted segment">
  <p>ARTIST: <span class="ui inverted spaced medium header"><%= @song.artist_name %></span></p>
  <p>ALBUM: <span class="ui inverted spaced medium header"><%= @song.album%></span></p>
  <p>RATING: <span class="ui inverted spaced medium header"> <%=@song.rating%></span></p>
  <p>COUNTRY: <span class="ui inverted spaced medium header"> <%=@song.country%></span></p>
  </div>
  <%# <h2>Comments</h2> %>
</div>
<br/>

<div class="ui three buttons">
  <%= link_to 'Edit song', edit_artist_song_path([@artist, @song]), class: "ui color3 button" %>
  <br/>
  <%= link_to 'Delete song', [@artist, @song], method: :delete, class: "ui color3 button" %>
  <br/>
  <%= link_to 'Back To All songs', artist_songs_path, class: "ui color3 button"%>
  <br/>
</div>

app/views/static_pages/home.html.erb
<h1></h1>
<p>Find me in app/views/static_pages/home.html.erb</p>